services:

  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  minio-init:
    image: minio/mc
    container_name: minio_init
    depends_on:
      minio:
        condition: service_healthy
    environment:
      - MINIO_USER=${MINIO_USER}
      - MINIO_PASSWORD=${MINIO_PASSWORD}
    entrypoint: >
      sh -c "
        mc alias set minio http://minio:9000 $${MINIO_USER} $${MINIO_PASSWORD} &&
        mc mb --ignore-existing minio/mlflow &&
        echo 'Bucket ready'
      "
    restart: "no"

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: mlflow_server
    depends_on:
      minio:
        condition: service_healthy
    environment:
      - MLFLOW_SERVER_ALLOWED_HOSTS=mlflow:5000,localhost:5000
      - AWS_ACCESS_KEY_ID=${MINIO_USER}
      - AWS_SECRET_ACCESS_KEY=${MINIO_PASSWORD}
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
    volumes:
      - mlflow_db:/mlflow/db
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5000')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  trainer:
    build: .
    container_name: trainer
    depends_on:
      mlflow:
        condition: service_healthy
      minio-init:
        condition: service_completed_successfully
    environment:
      - MODEL_PATH=/models/model.skops
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - AWS_ACCESS_KEY_ID=${MINIO_USER}
      - AWS_SECRET_ACCESS_KEY=${MINIO_PASSWORD}
    volumes:
      - model_data:/models
    command: ["python", "train.py"]
    restart: "no"

  api:
    build: .
    container_name: titanic_api
    depends_on:
      mlflow:
        condition: service_healthy
      trainer:
        condition: service_completed_successfully
    environment:
      - MODEL_PATH=/models/model.skops
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    ports:
      - "8000:8000"
    volumes:
      - model_data:/models
    command: >
      sh -c "
        uvicorn app.main:app --host 0.0.0.0 --port 8000
      "

volumes:
  mlflow_db:
  minio_data:
  model_data: